# Zika - Import

## Setup

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from IPython.display import display, Markdown
pd.set_option('display.max_columns', None)
sns.set_style('darkgrid')

SEED = 2026

## Dataset

In [5]:
df_zika = pd.read_csv("orig/train.csv")
display(Markdown("## `df_zika`"))
display(df_zika.shape)
display(df_zika.head(1))

## `df_zika`

(2138, 19)

,location,EW,EW_start_date,pop,cases,cases_est,cases_est_min,cases_est_max,p_rt1,p_inc100k,Sublocation,alert,id,model_version,tweet,Rt,receptivity,transmission,epidemic_threshold
0,A,201501,2015-01-04,12325232,0,0.0,0,0,0.5,0.0,0,1,355030820150119589,2023-08-20,0,0.0,0,0,0

In [ ]:
df_score = pd.read_csv("orig/test.csv")
display(Markdown("## `df_score`"))
display(df_score.shape)
display(df_score.head(1))

## `df_score`

(2138, 19)

,location,EW,EW_start_date,pop,cases,cases_est,cases_est_min,cases_est_max,p_rt1,p_inc100k,Sublocation,alert,id,model_version,tweet,Rt,receptivity,transmission,epidemic_threshold
0,A,201501,2015-01-04,12325232,0,0.0,0,0,0.5,0.0,0,1,355030820150119589,2023-08-20,0,0.0,0,0,0

In [ ]:
df_dengue = pd.read_csv("orig/dengue.csv")
display(Markdown("## `df_dengue`"))
display(df_dengue.shape)
display(df_dengue.head(1))

## `df_score`

(2138, 19)

,location,EW,EW_start_date,pop,cases,cases_est,cases_est_min,cases_est_max,p_rt1,p_inc100k,Sublocation,alert,id,model_version,tweet,Rt,receptivity,transmission,epidemic_threshold
0,A,201501,2015-01-04,12325232,0,0.0,0,0,0.5,0.0,0,1,355030820150119589,2023-08-20,0,0.0,0,0,0